modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="industrialwarfare"
version="0.5.0-alpha"
displayName="Industrial Warfare"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
credits="Made by rbasamoyai, artwork by rbasamoyai and zerokumo"
authors="rbasamoyai"
description='''Industrial Warfare, a warfare mod made by rbasamoyai'''

[[dependencies.industrialwarfare]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.industrialwarfare]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.industrialwarfare]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.27,)"
    ordering="NONE"
    side="BOTH"
